#! /bin/sh

### BEGIN INIT INFO
# Provides: tpagent
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: TopPatch Agent
# Description: Provides communication between the TopPatch agent and the TopPatch Server.
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=tpagentd
DESC="TopPatch Agent"
DAEMON=/opt/TopPatch/agent/daemon/agentd.py

set -e

case "$1" in
  start)
	python $DAEMON start
        ;;
  stop)
	python $DAEMON stop
	;;
  restart|reload|force-reload)
	python $DAEMON restart
	;;
  status)
	python $DAEMON status
	;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|status}" >&2
    exit 1
    ;;
esac

exit 0
