#!/usr/bin/env python

import os
import sys
import shutil
import filecmp
import subprocess

from optparse import OptionParser


def copy_install_script(installer):
    install_script_path = installer

    if not install_script_path:
        current_dir = os.path.dirname(__file__)
        install_script_path = os.path.join(current_dir, '..', 'install')

    # Avoids copying if files are the same
    if not filecmp.cmp(install_script_path, 'install'):
        shutil.copy(install_script_path, 'install')


def copy_agent_dir(agent_dir):
    dest = 'dist/TopPatch Agent Installer.app/Contents/Resources/agent'
    shutil.copytree(agent_dir, dest)


def build(pyinstaller_path, spec_path):
    cmd = ['/usr/bin/python', pyinstaller_path, '-w', spec_path, '-y']
    subprocess.call(cmd)


def main(args):
    #copy_install_script(args.agent_dir)
    build(args.pyinstaller, args.spec)
    copy_agent_dir(args.agent_dir)


def get_input():
    parser = OptionParser()
    parser.add_option("-p", dest="pyinstaller", default="",
                      help="Provide the path to pyinstaller.py")
    parser.add_option("-s", dest="spec", default="",
                      help="Provide the path to the spec file")
    parser.add_option("-a", dest="agent_dir", default="",
        help="Provide with the path to the agent directory to be used."
    )

    return parser.parse_args()


if __name__ == '__main__':
    args = get_input()[0]
    if not (args.pyinstaller and args.spec):
        sys.stderr.write(
            ("Please provide both the pyinstaller path and the"
             "spec file path to -p and -s, respectively.\n"))
        sys.exit(1)

    main(args)
