"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['../agent.py']
DATA_FILES = [('', ['../bin', '../certs', '../daemon', '../plugins',
                   '../src', '../deps', '../watcher_mac.py'])]

OPTIONS = {'argv_emulation': True,
           'iconfile' : 'favicon.icns',
           'plist' : 'Info.plist'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
